### ISSUE TITLE
__linux__ definition is not avaiable

### ISSUE THREAD

**Issue by venkatmakam** [xpack-dev-tools/riscv-none-elf-gcc-xpack#28]
### Description
I am trying to cross compile a c program to risc-v linux environment. My code is structured for cross compiler and depends on the pragma `__linux__` to know that the code is compiling for linux.

But with this compiler the pragma `__ linux __` is not defined. 
Do I need to define the pragma manually? what's the expected behavior for risc-v cross compilers.

### Versions

- [RISC-V GCC version] : NA
- [operating system] : windows 11

**Comment by ilg-ul** [comment]
> Note: Remove unnecessary text after reading, before entering your ticket.

Did you read this notice?

**Comment by venkatmakam** [comment]
> > Note: Remove unnecessary text after reading, before entering your ticket.
> 
> Did you read this notice?

sorry.. updated the issue description.

**Comment by ilg-ul** [comment]
> I am trying to cross compile a c program to risc-v linux environment ... the pragma __ linux __ is not defined.

That's correct, the xPack GNU RISC-V **Embedded** GCC is for embedded targets (like bare metal), not for linux.
