### ISSUE TITLE
Installation does not work.

### ISSUE THREAD

**Issue by greenscreenflicker** [xpack-dev-tools/riscv-none-elf-gcc-xpack#29]
### Description

I followed the installation instructions on the install section (https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack)
The code doesn't work.

### Steps to Reproduce

1. `xpm init`: No packages found.

2. `xpm install @xpack-dev-tools/riscv-none-elf-gcc@latest --verbose`: Package "@xpack-dev-tools/riscv-none-elf-gcc@latest" not found.
3. Tryed refereshing. Doesn't work either.
**Expected behaviour:** Should install

**Actual behaviour:** Doesn't install package.

### Versions

- [RISC-V GCC version]
- `lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy`

**Comment by ilg-ul** [comment]
Are you behind a firewall/proxy?

**Comment by greenscreenflicker** [comment]
I installed WSL2 on windows https://learn.microsoft.com/en-us/windows/wsl/install

I don't know,if there is any firewall. But apt under ubuntu wsl works.

See also: https://github.com/hathach/tinyusb/discussions/2525#discussioncomment-8895299

**Comment by ilg-ul** [comment]
Wrong tool. See https://xpack.github.io to install the correct xpm.

**Comment by greenscreenflicker** [comment]
And where exactly is the installtion tutorial? 
Found it: https://xpack.github.io/install/

**Comment by greenscreenflicker** [comment]
install worked. i propose to put a direct link on the front side on the project, so that install instructions are more easy to find.

**Comment by ilg-ul** [comment]
> put a direct link on the front side on the project

The existing one is not enough?

- https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack#prerequisites
