### ISSUE TITLE
Small typo in build instructions

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [xpack-dev-tools/riscv-none-elf-gcc-xpack#39]
See here:

- https://xpack-dev-tools.github.io/riscv-none-elf-gcc-xpack/docs/developer/#build-the-binaries

> About 73 minutes later, the output of the build script is a compressed archive and its SHA signature, created in the `buils-assets/build/linux-x64/deploy` folder:

should be 

> About 73 minutes later, the output of the build script is a compressed archive and its SHA signature, created in the `build-assets/build/linux-x64/deploy` folder:

I tried editing the page using the ["Edit this page" link](https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/edit/xpack/website/docs/developer/index.mdx) but it didn't show that text/typo so I presume that that's not the correct way to make changes?

![2024-12-04 17 10 17](https://github.com/user-attachments/assets/c974ff83-1dd2-46b1-ac8c-5d8159e2284a)

**Comment by ilg-ul** [comment]
Ah, right, this is a small typo.

> I tried editing the page using the "Edit this page" link...

The page should not be edited via that link, the website is generated from a template, and the edit must be performed in the template.

I fixed it and regenerated all 20+ sites.

Thank you for reporting this.

**Comment by TommyMurphyTM1234** [comment]
> > I tried editing the page using the "Edit this page" link...
> 
> The page should not be edited via that link, the website is generated from a template, and the edit must be performed in the template.

Should that link be removed to avoid confusion in that case?

> I fixed it and regenerated all 20+ sites.

Thanks.

**Comment by ilg-ul** [comment]
> Should that link be removed to avoid confusion in that case?

Probably. I have to figure out a way to do it.

**Comment by ilg-ul** [comment]
Can you try again the Edit link and tell me exactly what the error is? I guess the issue is triggered because you do not have write access to the repo.
